---
- name: 'Configure firewalld for HTTPS'
  firewalld:
    port: '{{ item }}'
    permanent: 'True'
    immediate: 'True'
    state: 'enabled'
  with_items:
    - '443/tcp'
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'

- name: 'Configure iptables for HTTPS'
  iptables:
    action: 'append'
    chain: 'INPUT'
    policy: 'ACCEPT'
    protocol: '{{ item.protocol }}'
    destination_port: '{{ item.dp }}'
    state: 'present'
  with_items:
    - { dp: '443', protocol: 'tcp' }
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '6'
