---
- name: 'Instal the EPEl-release repo'
  yum:
    name: 'epel-release'
    state: 'present'

- name: 'Install software required for Ansible server'
  yum:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'git'
    - 'ansible'
    - 'libselinux-python'
    - 'docker'
    - 'docker-python'
