---
# Add generic roles here
- hosts: 'localhost'
  user: 'root'
  roles:
    - 'intranet-root-certificates'

- hosts: 'kvm'
  roles:
    - 'kvm-hypervisor'

- hosts: 'dns-bind-01'
  roles:
    - 'bind-master'

- hosts: 'dhcp-isc-01'
  roles:
    - 'dhcp'

- hosts: 'pxe-cobbler-01'
  roles:
    - 'cobbler-centos7'

- hosts: 'vcs-git-01'
  roles:
    - 'ansible-server'

- hosts: 'backup-bacula-01'
  roles:
    - 'bacula'
