---
- name: 'restart httpd'
  service:
    name:  'httpd'
    state: 'restarted'
    enabled: 'yes'
  listen: 'restart Nagios'

- name: 'restart nagios'
  service:
    name: 'nagios'
    enabled: 'yes'
    state: 'restarted'
  listen: 'restart Nagios'
