---
- name: 'Install the rndc key'
  copy:
    src: 'rndc.key'
    dest: '/etc/'
    owner: 'root'
    group: 'named'
    mode: '0640'

- name: 'Configure Bind'
  template:
    src: 'named.conf.j2'
    dest: '/etc/named.conf'
    owner: 'root'
    group: 'named'
    mode: '0640'
    validate: 'named-checkconf %s'
  notify: 'Reload named-chroot'

- name: 'Check if the forward zone file has already been created. The file is dynamic so it cant be modified manually now'
  stat:
    path: '/var/named/dynamic/db.{{ domain }}.zone'
  register: forward_zone

- name: 'Configure the Bind forward zone'
  template:
    src: 'db.domain.zone.j2'
    dest: '/var/named/dynamic/db.{{ domain }}.zone'
    owner: 'root'
    group: 'named'
    mode: '0640'
    validate: 'named-checkzone {{ domain }} %s'
  notify: 'Restart named-chroot'
  when: not forward_zone.stat.exists

- name: 'Check if the reverse zone file has already been created. The file is dynamic so it cant be modified manually now'
  stat:
    path: '/var/named/dynamic/db.{{ domain }}.rr.zone'
  register: reverse_zone

- name: 'Configure the Bind reverse zone'
  template:
    src: 'db.domain.rr.zone.j2'
    dest: '/var/named/dynamic/db.{{ domain }}.rr.zone'
    owner: 'root'
    group: 'named'
    mode: '0640'
    validate: 'named-checkzone {{ reverse_dns }} %s'
  notify: 'Restart named-chroot'
  when: not reverse_zone.stat.exists

- name: 'Configure /etc/resolv.conf to point locally'
  template:
    src: 'resolv.conf.j2'
    dest: '/etc/resolv.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
