---
- name: 'Ensure the gpg directory exists'
  file:
    path: '/etc/pki/rpm-gpg'
    state: 'directory'

- name: 'Copy the GPG keys'
  copy:
    src: 'RPM-GPG-KEY-EPEL-7'
    dest: '/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Check if EPEl gpg key is installed'
  shell: "rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n' | grep EPEL"
  changed_when: False
  register: 'EPEL_Installed'

- name: 'Install the EPEL rpm gpg key'
  command: 'rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7'
  when: EPEL_Installed.rc != 0
