---
# This configuration is required to allow an approved user
# to access the libvirt API on the virualization host over SSH
- name: 'Add the libvirt group'
  group:
    name: 'libvirt'
    state: 'present'

- name: 'Add the admin account {{ admin }} to the libvirt group'
  user:
    name: '{{ admin }}'
    groups: 'libvirt'
    append: 'yes'
    state: 'present'
