---
# This configuration is required to allow an approved user
# to access the libvirt API on the virualization host over SSH
- name: 'Configure the libvirtd service'
  copy:
    src: 'libvirtd.conf'
    dest: '/etc/libvirt/'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Restart libvirtd'
