---
- name: 'Check if the host supports CPU Hardware Virtualization'
  command: "/usr/bin/grep -E '(vmx|svm)' /proc/cpuinfo"
  register: 'virtualization_supported'
  changed_when: False

- name: 'Stop the playbook if the host doesnt support Hardware Virtualization'
  fail:
    msg: 'The system does not support CPU Hardware Virtualization'
  when: virtualization_supported.rc == 1
  df
